version: "3.1"
services:
  server:
    container_name: 'excercise_server'
    build: ./server
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    depends_on:
      - db
  db:
    image: "postgres:13"
    container_name: "excercise_db"
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
    # env_file: .env