version: "3.1"
services:
  client:
    container_name: 'excercise_client'
    build: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file: .env
    depends_on:
      - server
  server:
    container_name: 'excercise_server'
    build: ./server
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    depends_on:
      - db
  db:
    image: "postgres:13"
    container_name: "excercise_db"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}